{% set name = "pymedphys" %}
{% set version = "0.7.1" %}
{% set file_ext = "tar.gz" %}
{% set hash_type = "sha256" %}
{% set hash_value = "25912f34ada1dd404eb3809a0d3697c2b60dfecd6b4405019cc562d8ada3f8b5" %}

package:
  name: '{{ name|lower }}'
  version: '{{ version }}'

source:
  fn: '{{ name }}-{{ version }}.{{ file_ext }}'
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ file_ext }}
  '{{ hash_type }}': '{{ hash_value }}'

build:
  number: 0
  noarch: python
  script: "python -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"

requirements:
  build:
    - python>=3.6
    - pip
    - pytest-runner
  run:
    - attrs
    - dataclasses; python_version=="3.6"
    - keyring
    - matplotlib
    - notebook
    - numpy <1.16, >=1.12
    - pandas
    - Pillow
    - psutil
    - pydicom>=1.0
    - pymssql
    - python>=3.6
    - python-dateutil
    - scipy
    - shapely
    - xarray
    - xlwings; platform_system != "Linux"

test:
  imports:
    - pymedphys

about:
  home: https://pymedphys.com
  license: GNU Affero General Public v3 or later (AGPL-3.0+)
  license_family: AGPL
  license_file: LICENSE
  summary: Medical Physics Python toolbox

extra:
  recipe-maintainers:
    - SimonBiggs
